### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by malmans2**
New features:

- Use `pydocstyle` in pre-commit
- Add basics documentation that automatically builds API
- Add `make build-docs`
- Add step in GH workflow to check that the documentation can be compiled

### CODE REVIEW

**Review by alexamici — APPROVED** [review]
Very good. I have only one nitpick: do we really need `make.bat`?

**Comment by malmans2** [comment]
There's ongoing work to better handle this make files in sphinx: https://github.com/sphinx-doc/sphinx/issues/5618
I would leave it for now, so it's clear which version of sphinx we used to create the template, and I would remove it as soon as this changes in Sphinx. I'll keep an eye on it!

**Review by EddyCMWF — APPROVED** [review]
Again just a small comment, can you mention that the template includes documentation in the top-level README.md, and possible include a link to the sphinx tutorial instructions.... as I type I see the PR has been merged, can you do this anyway?

**Comment by malmans2** [comment]
> Again just a small comment, can you mention that the template includes documentation in the top-level README.md, and possible include a link to the sphinx tutorial instructions.... as I type I see the PR has been merged, can you do this anyway? https://www.sphinx-doc.org/en/master/tutorial/

Thanks, and I've done both suggestions. I quickly merged so the whole team can test this. Let me know if you have more suggestions to improve the template.

**Pull request merged**
